library(igraph)
G2=read.csv("/home/kapil/desktop/study material notes/6TH SEM/Social Network Analysis/lab/assignment-3/17bcs013(degree_distribution)/real_world_networks/karate.csv")
a=data.frame(G2)
G=graph_from_data_frame(a)
t = table(degree(G))
plot(t , xlab="Degree", ylab="Frequency")
