library(igraph)
library(png)
G=graph(c(1,"A",2,"B",3,"C",2,"A",1,"C"),directed=F)
V(G)$type=c(T,F,T,F,T,F)
V(G)$color=ifelse(V(G)$type,"lightblue","salmon")
V(G)$shape=ifelse(V(G)$type,"square","circle")
plot(G,layout=layout.bipartite,edge.color="red")
img1 = readPNG("/home/kapil/desktop/study material notes/6TH SEM/Social Network Analysis/lab/class2/class2_dolphin/dolphin.png")
V(G)$raster = replicate(vcount(G),img1,simplify=T)
plot(G,vertex.shape="raster",vertex.label=NA,layout=layout.bipartite)